### ISSUE TITLE
How can I convert a diffrent dataset into the format that it can be used to fine-tune the TAPAS model?

### ISSUE THREAD

**Issue by shabbie** [google-research/tapas#132]
I want to fine-tune the TAPAS WTQ model on another dataset then the ones which have been provided. How can I convert the dataset into the format that it can be used to fine-tune the model? I have tried creating a data folder having a tsv file name 'training.tsv' containing [id, question, link to the table, target value] as prescribed in the WTQ repo. But I am facing this error when calling the 'create_data' mode in run_task_main.py.
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/run_task_main.py", line 813, in <module>
    app.run(main)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/run_task_main.py", line 767, in main
    token_selector)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/utils/task_utils.py", line 140, in create_interactions
    wtq_utils.convert(input_dir, output_dir)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/utils/wtq_utils.py", line 240, in convert
    _convert_data(table_cache, input_dir, output_dir, train_file, version)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/utils/wtq_utils.py", line 167, in _convert_data
    table = _read_wtq_table(input_dir, wtq_table_id)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/tapas/utils/wtq_utils.py", line 95, in _read_wtq_table
    dtype='str',
  File "/data/Shabbir/rop/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/data/Shabbir/rop/lib/python3.6/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 929, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 916, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2071, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2`

This is while reading the table data is what I can get from the error trace.

**Comment by eisenjulian** [comment]
Hi @shabbie ,
This the code that reads each individual table from WikiTableQuestions in `utils/wtq_utils.py`:
```python
def _read_wtq_table(input_dir: Text, wtq_table_id: Text) -> pd.DataFrame:
  """Reads table file as pandas frame."""
  table_path = os.path.join(input_dir, wtq_table_id)
  with tf.io.gfile.GFile(table_path, 'r') as table_in:
    return pd.read_csv(
        table_in,
        delimiter=',',
        escapechar='\\',
        dtype='str',
    )
```
Apparently there's something wrong with the format of your csv file, perhaps something is not escaped correctly, You can add a try catch there in `_read_wtq_table` to see which file has the problem. Let me know if you need any further help!
