### ISSUE TITLE
Error: Getting Requirements to Build Wheel Failed

### ISSUE THREAD

**Issue by srirammadduri-ts** [google-research/tapas#176]
I encountered an error while attempting to install Tapas on macOS using pip. The installation process failed with the following error message:
<img width="1445" alt="Screenshot 2023-05-16 at 1 05 11 PM" src="https://github.com/google-research/tapas/assets/133745997/910518f2-9c69-489f-a2d4-910c4e289309">

Steps to Reproduce:

1. Clone the Tapas repository. `git clone https://github.com/google-research/tapas`
2. Navigate to the repository directory. `cd tapas `
3. Run the command `pip install -e .` to install Tapas.

Error:

```
Obtaining file:///Users/sriram.madduri/Desktop/thoughtspot/tapas
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting apache-beam[gcp]==2.28.0 (from tapas-table-parsing==0.0.1.dev0)
  Using cached apache-beam-2.28.0.zip (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/Users/sriram.madduri/Desktop/nl2sage/tapex/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sriram.madduri/Desktop/nl2sage/tapex/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sriram.madduri/Desktop/nl2sage/tapex/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 526, in get_distribution
          dist = get_provider(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 398, in get_provider
          return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 966, in require
          needed = self.resolve(parse_requirements(requirements))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/74/z78x6kh53ws08tdzt2x4k4xm0000gp/T/pip-build-env-_16z4wui/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
          raise DistributionNotFound(req, requirers)
      pkg_resources.DistributionNotFound: The 'pip' distribution was not found and is required by the application
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by zyt0328** [comment]
I have the same problem, have you tried to run it in other system environments？
