### ISSUE TITLE
Run on Custom data

### ISSUE THREAD

**Issue by mdmustafizurrahman** [google-research/tapas#22]
I tried to run the custom data mentioned in the ipython notebook example in this repository. In that example the code converts a table and queries directly to the tfexamples. Now when I run the code to do prediction I get the following error

`E0617 16:23:59.204641 139751394191168 error_handling.py:70] Error recorded from prediction_loop: 2 root error(s) found.
  (0) Data loss: inflate() failed with error -3: incorrect header check
         [[node IteratorGetNext (defined at /data/t-mdra/projects/tapas/tapas/experiments/prediction_utils.py:199) ]]
         [[IteratorGetNext/_1269]]
  (1) Data loss: inflate() failed with error -3: incorrect header check
         [[node IteratorGetNext (defined at /data/t-mdra/projects/tapas/tapas/experiments/prediction_utils.py:199) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "tapas/run_task_main.py", line 776, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tapas/run_task_main.py", line 761, in main
    loop_predict=FLAGS.loop_predict,
  File "tapas/run_task_main.py", line 467, in _train_and_predict
    global_step=current_step,
  File "tapas/run_task_main.py", line 516, in _predict
    global_step=None,
  File "tapas/run_task_main.py", line 575, in _predict_for_set
    cell_classification_threshold=_CELL_CLASSIFICATION_THRESHOLD)
  File "/data/t-mdra/projects/tapas/tapas/experiments/prediction_utils.py", line 199, in write_predictions
    for prediction in predictions:
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2913, in predict
    yield_single_examples=yield_single_examples):
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 617, in predict
    input_fn, ModeKeys.PREDICT)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 994, in _get_features_from_input_fn
    result, _, hooks = estimator_util.parse_input_fn_result(result)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/util.py", line 65, in parse_input_fn_result
    result = iterator.get_next()
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1947, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/t-mdra/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: inflate() failed with error -3: incorrect header check
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_1269]]
  (1) Data loss: inflate() failed with error -3: incorrect header check
         [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

`

**Comment by nopper** [comment]
Hi @mdmustafizurrahman,

Can you share the notebook or the code you are using so we can try to reproduce the issue from our side?

**Comment by mdmustafizurrahman** [comment]
Thanks I have been able to resolve it. For prediction using the pretrained model I did not specify the compression type but after specifying that it worked.
