### ISSUE TITLE
Questions about fine-tuning on the TABFACT task

### ISSUE THREAD

**Issue by wcc17864158993** [google-research/tapas#96]
Hi, I have found a question when I was running the codes with "predict_and_evluate" mode.

If I used the following commands: 

```
! python3 tapas-master/tapas/run_task_main.py \
  --task="TABFACT" \
  --output_dir="results_data" \
  --model_dir="med_reset" \
  --init_checkpoint="tapas_medium_model/model.ckpt" \
  --bert_config_file="tapas_medium_model/bert_config.json" \
  --mode="predict_and_evaluate"
```
the error would be
```
Traceback (most recent call last):
  File "tapas-master/tapas/run_task_main.py", line 819, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tapas-master/tapas/run_task_main.py", line 804, in main
    loop_predict=FLAGS.loop_predict,
  File "tapas-master/tapas/run_task_main.py", line 502, in _train_and_predict
    global_step=current_step,
  File "tapas-master/tapas/run_task_main.py", line 553, in _predict
    global_step=None,
  File "tapas-master/tapas/run_task_main.py", line 614, in _predict_for_set
    output_token_probabilities=False)
TypeError: write_predictions() got an unexpected keyword argument 'output_token_probabilities'
```
However if I used commands from the TAPAS package, it will run correctly. 
```
! python3 -m tapas.run_task_main \
  --task="TABFACT" \
  --output_dir="results_data" \
  --model_dir="med_reset" \
  --init_checkpoint="tapas_medium_model/model.ckpt" \
  --bert_config_file="tapas_medium_model/bert_config.json" \
  --mode="predict_and_evaluate"
```

Could you please help me with this issue?

**Comment by thomasmueller-google** [comment]
Thanks for reporting. Maybe that's a problem with the current release. We'll have a look!

**Comment by eisenjulian** [comment]
I think this is a problem with having two different versions of the code in python at the same time. The output_token_probabilities argument was added in a recent version that hasn't been released in the PyPI package yet, but when you launch the code with python3 tapas-master/tapas/run_task_main.py it's most likely using the pip package and not the files in your checked out repository. I recommend choosing one of the two. If you want to run locally you will have to uninstall the version you have from PyPI (pip uninstall tapas-table-parsing) and then install the version you have checked out (pip install -e ./tapas-master)

Let us know if this solves your issue

**Comment by wcc17864158993** [comment]
Thanks for your replay! I has solved this problems,but when I was running the codes with "predict_and_evluate" mode.

If I used the following commands:

```
! python3 tapas-master/tapas/run_task_main.py \
  --task="TABFACT" \
  --output_dir="results_data" \
  --model_dir="med_max_seq_length512" \
  --init_checkpoint="tapas_medium_model/model.ckpt" \
  --bert_config_file="tapas_medium_model/bert_config.json" \
  --mode="predict_and_evaluate"
```

the another error would be

```
WARNING:tensorflow:Reraising captured error
W1204 10:15:49.643929 140315625756480 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Key: prev_label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_919]]
  (1) Invalid argument: Key: prev_label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tapas-master/tapas/run_task_main.py", line 821, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tapas-master/tapas/run_task_main.py", line 806, in main
    loop_predict=FLAGS.loop_predict,
  File "tapas-master/tapas/run_task_main.py", line 504, in _train_and_predict
    global_step=current_step,
  File "tapas-master/tapas/run_task_main.py", line 555, in _predict
    global_step=None,
  File "tapas-master/tapas/run_task_main.py", line 616, in _predict_for_set
    output_token_probabilities=False)
  File "/data-output/tapas-master/tapas/experiments/prediction_utils.py", line 397, in write_predictions
    for prediction in predictions:
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in predict
    rendezvous.raise_errors()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3120, in predict
    yield_single_examples=yield_single_examples):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 631, in predict
    preds_evaluated = mon_sess.run(predictions)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Key: prev_label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_919]]
  (1) Invalid argument: Key: prev_label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
```

Could you please help me with this issue?
